import 'package:flutter/material.dart';

//색 데이터 리스트
Map<String, Color> colorMap = {
  "grey": Colors.grey,
  "blueGrey": Colors.blueGrey,
  "blue": Colors.blue,
  "blueAccent": Colors.blueAccent,
  "lightBlue": Colors.lightBlue,
  "lightBlueAccent": Colors.lightBlueAccent,
  "cyan": Colors.cyan,
  "cyanAccent": Colors.cyanAccent,
  "indigo": Colors.indigo,
  "indigoAccent": Colors.indigoAccent,
  "red": Colors.red,
  "redAccent": Colors.redAccent,
  "pink": Colors.pink,
  "pinkAccent": Colors.pinkAccent,
  "green": Colors.green,
  "greenAccent": Colors.greenAccent,
  "lightGreen": Colors.lightGreen,
  "lightGreenAccent": Colors.lightGreenAccent,
  "teal": Colors.teal,
  "tealAccent": Colors.tealAccent,
  "purple": Colors.purple,
  "purpleAccent": Colors.purpleAccent,
  "deepPurple": Colors.deepPurple,
  "deepPurpleAccent": Colors.deepPurpleAccent,
  "yellow": Colors.yellow,
  "yellowAccent": Colors.yellowAccent,
  "lime": Colors.lime,
  "limeAccent": Colors.limeAccent,
  "amber": Colors.amber,
  "amberAccent": Colors.amberAccent,
  "orange": Colors.orange,
  "orangeAccent": Colors.orangeAccent,
  "deepOrange": Colors.deepOrange,
  "deepOrangeAccent": Colors.deepOrangeAccent,
  "brown": Colors.brown,
  "white": Colors.white,
  "white70": Colors.white70,
  "white60": Colors.white60,
  "white54": Colors.white54,
  "white30": Colors.white30,
  "white24": Colors.white24,
  "white12": Colors.white12,
  "white10": Colors.white10,
  "black": Colors.black,
  "black87": Colors.black87,
  "black54": Colors.black54,
  "black45": Colors.black45,
  "black38": Colors.black38,
  "black26": Colors.black26,
  "black12": Colors.black12,
};

List<Color> colorList = [
  Colors.grey,
  Colors.blueGrey,
  Colors.blue,
  Colors.blueAccent,
  Colors.lightBlue,
  Colors.lightBlueAccent,
  Colors.cyan,
  Colors.cyanAccent,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.red,
  Colors.redAccent,
  Colors.pink,
  Colors.pinkAccent,
  Colors.green,
  Colors.greenAccent,
  Colors.lightGreen,
  Colors.lightGreenAccent,
  Colors.teal,
  Colors.tealAccent,
  Colors.purple,
  Colors.purpleAccent,
  Colors.deepPurple,
  Colors.deepPurpleAccent,
  Colors.yellow,
  Colors.yellowAccent,
  Colors.lime,
  Colors.limeAccent,
  Colors.amber,
  Colors.amberAccent,
  Colors.orange,
  Colors.orangeAccent,
  Colors.deepOrange,
  Colors.deepOrangeAccent,
  Colors.brown,
  Colors.white,
  Colors.white70,
  Colors.white60,
  Colors.white54,
  Colors.white30,
  Colors.white24,
  Colors.white12,
  Colors.white10,
  Colors.black,
  Colors.black87,
  Colors.black54,
  Colors.black45,
  Colors.black38,
  Colors.black26,
  Colors.black12,
];
